### ISSUE TITLE
Implement monorepo

### ISSUE THREAD

**Issue by rodber** [chevere/chevere#13]
A monorepo will allow to automatically split components allowing users to progressively use the framework. By doing this, each individual component can be used stand-alone from the rest of the framework (or at least from any unnecessary file).

- [ ] Split components each one to a new repo  `chevere/`<componentName>`
- [ ] Repo interfaces at `chevere/interfaces`
- [ ] Repo exceptions at `chevere/exceptions`
- [ ] Setup monorepo

**Comment by peter279k** [comment]
Here are some monorepo references on GitHub Actions:

- https://github.com/phootwork/phootwork/blob/master/.github/workflows/monorepo_split.yml
- https://github.com/phootwork/phootwork/blob/master/.github/workflows/split_releases.yml

**Comment by rodolfoberrios** [comment]
That's great, I've also find a series of post for php-specific monorepo tools: https://tomasvotruba.com/blog/2020/06/15/how-to-create-monorepo-from-existing-repositories-in-7-steps/

What I do like about that approach is the extended language support, plus versioning 🤩
