### ISSUE TITLE
Path validation issues on Windows platform

### ISSUE THREAD

**Issue by Rarst** [chevere/chevere#68]
Trying to start the server, there are couple errors where path validation doesn't let (valid) paths pass.

Windows paths _can_ start with `/` (it would be current-drive-relative path) but that's not common and generated path in this case starts with a drive letter:

```
C:\server>php vendor/chevere/xr/server.php -p 27420
� Building v0.2.1 (Egocéntrico)
Chevere\Filesystem\Exceptions\FilesystemException thrown in C:\server\vendor\chevere\chevere\src\Filesystem\functions.php:57

# └ Chevere\Filesystem\Exceptions\PathNotAbsoluteException thrown
Path C:\server\vendor\chevere\xr/app/src\ must start with / in C:\server\vendor\chevere\chevere\src\Filesystem\AssertPathFormat.php:42

# Message
Unable to create a Chevere\Filesystem\Dir for C:\server\vendor\chevere\xr/app/src\

# Incident ID:62138590af1d2

# Time
2022-02-21T12:29:04+00:00 [1645446544]

# Stack trace
------------------------------------------------------------
#0 C:\server\vendor\chevere\chevere\src\Filesystem\functions.php:57
{main}()
------------------------------------------------------------
chevere/xr#1 C:\server\vendor\chevere\xr\server.php:120
Chevere\Filesystem\dirForPath(string(length=36))
------------------------------------------------------------

# Server
Windows NT RDESKTOP 10.0 build 19043 (Windows 10) AMD64
4
```

Windows accepts either slash in path really, but `DIRECTORY_SEPARATOR` is set to more common `\` and generated path doesn't fit in this case:
```
C:\server>php vendor/chevere/xr/server.php -p 27420
� Building v0.2.1 (Egocéntrico)
Chevere\Filesystem\Exceptions\PathTailException thrown in C:\server\vendor\chevere\chevere\src\Filesystem\Dir.php:148

# Message
Instance of Chevere\Filesystem\Path must provide an absolute path ending with \, path C:\server\vendor\chevere\xr/app/build/ provided

# Incident ID:621386230f6d4

# Time
2022-02-21T12:31:31+00:00 [1645446691]

# Stack trace
------------------------------------------------------------
#0 C:\server\vendor\chevere\chevere\src\Filesystem\Dir.php:148
{main}()
------------------------------------------------------------
chevere/xr#1 C:\server\vendor\chevere\chevere\src\Filesystem\Dir.php:39
Chevere\Filesystem\Dir->assertTailDir()
------------------------------------------------------------
chevere/xr#2 C:\server\vendor\chevere\chevere\src\Filesystem\File.php:162
Chevere\Filesystem\Dir->__construct(Chevere\Filesystem\Path(#84))
------------------------------------------------------------
chevere/xr#3 C:\server\vendor\chevere\chevere\src\Filesystem\File.php:126
Chevere\Filesystem\File->createPath()
------------------------------------------------------------
chevere/xr#4 C:\server\vendor\chevere\xr\server.php:126
Chevere\Filesystem\File->create()
------------------------------------------------------------

# Server
Windows NT RDESKTOP 10.0 build 19043 (Windows 10) AMD64
```

I am not sure if this is upstream relative to xr, because the checks are not unsound, but they would depend on paths generated and provided formatted to a Linux convention in Windows environment, which xr doesn't seem to do in these cases.

**Comment by Rarst** [comment]
Gotcha. I had just commented the parts out trying to get xr to start, so I don't have anything to PR or I would just do that.

From my experience with such issues the path of least maintenance is to normalize paths on Windows before any comparison or manipulation:
1. If path starts with drive letter, normalize the letter case of it (to either, as long as it's consistent).
2. Normalize slashes to Linux forward slashes, there isn't really a point to specifically support Windows slashes or both kinds at the same time.

**Comment by rodber** [comment]
To support Windows I need to setup a virtual environment + a Windows based CI testing to ensure that the code will keep working with updates. I tried running a hosted runner but I was unable to replicate the issue (my bet is that the runner doesn't run the same fs existing on windows).

```
| Time: 00:00.432, Memory: 8.00 MB
| 
| OK (201 tests, 574 assertions)
[Test/PHP 8.0 test on windows-2022-1]   ✅  Success - Run tests with phpunit
```

I've a laptop somewhere with Windows 10, will give it a try once it finish updating itself.

By the way, if you (or someone reading) knows how to easy run Windows for this purpose please let me know (Macos, Ubuntu).

**Comment by rodber** [comment]
@Rarst Could you try with [0439b82](https://github.com/chevere/chevere/commit/0439b82fc6df4aa9bd1a3107431ed175e351ec91)

**Comment by Rarst** [comment]
Seems to resolve `PathNotAbsoluteException` ! Following `PathTailException` still there.

**Comment by rodber** [comment]
@Rarst Could you try with [a2cf82e](https://github.com/chevere/chevere/commit/a2cf82e72bde536fd49e4ba37141f37cc8dc3d84)

**Comment by Rarst** [comment]
That got xr starting for me, cheers! 👍
