### ISSUE TITLE
update to latest thecodingmachine/safe

### ISSUE THREAD

**Issue by michabbb** [chevere/chevere#82]
hi,

would it be possible to update `thecodingmachine/safe` in your composer or at least allow newer versions ?
i am unable to install other packages because of that old version. newest is `2.2.1`.

thanks!

**Comment by rodber** [comment]
Cool.

```json
"thecodingmachine/safe": "^2"
```

**Comment by rodber** [comment]
😢 Seems that it broke my mutation testing.

https://github.com/chevere/chevere/runs/7344004833?check_suite_focus=true

**Comment by rodber** [comment]
https://github.com/chevere/chevere/releases/tag/0.8.1
